[project]
name = "hexchess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.2",
    "pre-commit>=4.2.0",
    "ruff>=0.11.12",
]
